-- Esquema inicial para el agente editorial de ChequeaBolivia.
-- Ejecutar en Supabase > SQL Editor > New query.
-- Recomendación: mantener SUPABASE_SERVICE_ROLE_KEY solo en Vercel, nunca en el navegador.

create extension if not exists "pgcrypto";

create table if not exists public.verification_cases (
  id uuid primary key default gen_random_uuid(),
  titulo_conclusion text,
  categoria text not null default 'Falso',
  contexto text,
  que_circula text,
  que_verificamos text,
  hallazgos_evidencia text,
  conclusion_categoria text,
  fuentes text,
  notas_editoriales text,
  estado text not null default 'borrador',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.verification_cases(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.drafts (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.verification_cases(id) on delete cascade,
  draft_json jsonb not null,
  texto_completo text,
  alertas_editoriales text[] default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.approved_versions (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.verification_cases(id) on delete cascade,
  final_text text not null,
  approved_by text,
  notes text,
  approved_at timestamptz not null default now()
);

create table if not exists public.style_examples (
  id bigint generated by default as identity primary key,
  case_id uuid references public.verification_cases(id) on delete set null,
  title text,
  category text,
  final_text text not null,
  notes text,
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists verification_cases_categoria_idx on public.verification_cases(categoria);
create index if not exists verification_cases_estado_idx on public.verification_cases(estado);
create index if not exists chat_messages_case_id_idx on public.chat_messages(case_id);
create index if not exists drafts_case_id_idx on public.drafts(case_id);
create index if not exists approved_versions_case_id_idx on public.approved_versions(case_id);
create index if not exists style_examples_category_idx on public.style_examples(category);
create index if not exists style_examples_approved_idx on public.style_examples(approved);
